
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      RAM_SIZE: "10G"
      CPU_CORES: "10"
      # LANGUAGE: "Russian"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - ./config/bin:/storage
      - ./config/startup:/oem
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #             - gpu
    #             - compute
    #         - driver: nvidia
    #           #device_ids: ['0']
    #           capabilities: [gpu]

