apiVersion: v1
kind: Namespace
metadata:
  name: headscale
---
apiVersion: v1
kind: Service
metadata:
  name: headscale-external
  namespace: headscale
spec:
  ports:
    - port: 9090  # Порт, который будет использоваться внутри кластера
      targetPort: 9090  # Порт на хостовой системе
---
apiVersion: v1
kind: Endpoints
metadata:
  name: headscale-external
  namespace: headscale
subsets:
  - addresses:
      - ip: 192.168.88.252  # Укажите IP хостовой системы
    ports:
      - port: 9090  # Порт Headscale на хостовой системе
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headscale-ingress
  namespace: headscale
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    #traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
    - host: tail.domain.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headscale-external
                port:
                  number: 9090  # Порт Service
  tls:
      - hosts:
          - tail.domain.xyz
        secretName: headscale-tls
